#!/bin/bash
# Consume workloads generated by gen_simul_skew.sh and run the 7-workload
# parallel experiment for each rnum sweep and iteration found under
# $BASE_DIR/workloads/rnum_<S>/<NNN>/.
#
# Usage: ./run_simul_skew.sh [BASE_DIR]
#   BASE_DIR defaults to ./results_skew
#
# Semantics of RNUM (0..TASKNUM):
#   With TASKNUM=4 and RNUM=S, the taskset has:
#     S       read-intensive tasks
#     4 - S   write-intensive tasks
#
# argv[10] passed to the simulator = TASKNUM - RNUM so that
# generate_taskset_skew2 sees "# of WRITE-intensive tasks".
# The same value is forwarded at runtime so RR_job_start_q's `skewnum`
# comparison matches the generated taskset polarity.
#
# Behaviour:
#   - Auto-extracts $BASE_DIR/workloads.tar.gz if the workloads/ dir is missing.
#   - Iterates every "<NNN>" directory that has a `.done` marker.
#   - After all iterations finish, tar.gz's the workloads/ dir and deletes the
#     raw copy to save disk. tar.gz is skipped if any iteration failed.
#
# Output layout:
#   $BASE_DIR/rnum_<S>/<workload>/<prefix>_rrchecker_<NNN>.csv   (per iter)
#   $BASE_DIR/rnum_<S>/<workload>/<prefix>_updaterate_<NNN>.csv  (per iter)
#   $BASE_DIR/rnum_<S>/<workload>/<prefix>_lifetime.csv          (appended)
#   $BASE_DIR/rnum_<S>/<workload>/<prefix>_overhead.csv          (appended)

set -u

BASE_DIR="${1:-./results_skew}"
BIN="$(readlink -f ./statesimul.out)"

U=0.3
TASKNUM=4
SKEWTYPE=1
RNUMS=(0 1 2 3 4)

if [ ! -x "$BIN" ]; then
    echo "error: $BIN not found or not executable" >&2
    exit 1
fi

WORKLOADS_DIR="$BASE_DIR/workloads"

if [ ! -d "$WORKLOADS_DIR" ] && [ -f "$BASE_DIR/workloads.tar.gz" ]; then
    echo "[INFO] extracting $BASE_DIR/workloads.tar.gz"
    tar xzf "$BASE_DIR/workloads.tar.gz" -C "$BASE_DIR"
fi

if [ ! -d "$WORKLOADS_DIR" ]; then
    echo "error: $WORKLOADS_DIR not found. Run gen_simul_skew.sh first." >&2
    exit 1
fi

WRITERANK_ABS="$(readlink -f ./writerank.csv 2>/dev/null || true)"
overall_rc=0

for S in "${RNUMS[@]}"; do
    WNUM_ARG=$(( TASKNUM - S ))
    RNUM_SRC="$WORKLOADS_DIR/rnum_$S"
    RNUM_BASE="$BASE_DIR/rnum_$S"

    if [ ! -d "$RNUM_SRC" ]; then
        echo "  warn: no workloads for rnum=$S at $RNUM_SRC; skipping" >&2
        continue
    fi

    mkdir -p "$RNUM_BASE"/{baseline,dynamic,static,hybrid,wonly,LaWL-D,LaWL}
    echo "########## read-intensive tasks = $S (write=$WNUM_ARG, util=$U -> $RNUM_BASE) ##########"

    for GENDIR in "$RNUM_SRC"/*/; do
        GENDIR="${GENDIR%/}"
        [ -f "$GENDIR/.done" ] || continue
        IDX=$(basename "$GENDIR")
        echo "=== [rnum=$S] iteration $IDX  ($(date '+%F %T')) ==="

        make_workdir() {
            local wd="$RNUM_BASE/$1/_run_$IDX"
            mkdir -p "$wd"
            for f in "$GENDIR"/taskparam.csv "$GENDIR"/cyc.csv "$GENDIR"/loc.csv \
                     "$GENDIR"/wr_t*.csv     "$GENDIR"/rd_t*.csv; do
                [ -e "$f" ] || continue
                ln -sf "$(readlink -f "$f")" "$wd/$(basename "$f")"
            done
            if [ -n "$WRITERANK_ABS" ] && [ -e "$WRITERANK_ABS" ]; then
                ln -sf "$WRITERANK_ABS" "$wd/writerank.csv"
            fi
            echo "$wd"
        }
        WD_BASELINE=$(make_workdir baseline)
        WD_DYNAMIC=$(make_workdir  dynamic)
        WD_STATIC=$(make_workdir   static)
        WD_HYBRID=$(make_workdir   hybrid)
        WD_WONLY=$(make_workdir    wonly)
        WD_LAWLD=$(make_workdir    LaWL-D)
        WD_LAWL=$(make_workdir     LaWL)

        ( cd "$WD_BASELINE" && taskset -c 9  "$BIN" NO     NO        SKIPRR  nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid1=$!
        ( cd "$WD_DYNAMIC"  && taskset -c 10 "$BIN" NO     MOTIVALLY SKIPRR  nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid2=$!
        ( cd "$WD_STATIC"   && taskset -c 11 "$BIN" NO     NO        BASE005 nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid3=$!
        ( cd "$WD_HYBRID"   && taskset -c 12 "$BIN" NO     MOTIVALLY BASE005 nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid4=$!
        ( cd "$WD_WONLY"    && taskset -c 13 "$BIN" NO     INVW      SKIPRR  nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid5=$!
        ( cd "$WD_LAWLD"    && taskset -c 14 "$BIN" UTILGC INVW      SKIPRR  nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid6=$!
        ( cd "$WD_LAWL"     && taskset -c 15 "$BIN" UTILGC INVW      RR005   nogen "$TASKNUM" "$U" "$SKEWTYPE" 0.05 0.95 "$WNUM_ARG" > /dev/null 2> run.err ) &
        pid7=$!

        rc=0
        for pid in $pid1 $pid2 $pid3 $pid4 $pid5 $pid6 $pid7; do
            wait "$pid" || rc=$?
        done
        if [ "$rc" -ne 0 ]; then
            echo "  warn: at least one workload exited non-zero in rnum=$S iter $IDX" >&2
            overall_rc=$rc
        fi

        collect() {
            local name="$1" prefix="$2" wd="$3"
            local dest="$RNUM_BASE/$name"

            for kind in rrchecker updaterate; do
                local src="$wd/${prefix}_${kind}.csv"
                [ -f "$src" ] && mv "$src" "$dest/${prefix}_${kind}_${IDX}.csv"
            done
            for kind in lifetime overhead; do
                local src="$wd/${prefix}_${kind}.csv"
                [ -f "$src" ] && cat "$src" >> "$dest/${prefix}_${kind}.csv"
            done
            if [ -s "$wd/run.err" ]; then
                mv "$wd/run.err" "$dest/run_${IDX}.err"
            fi
            rm -rf "$wd"
        }

        collect baseline Baseline "$WD_BASELINE"
        collect dynamic  Dynamic  "$WD_DYNAMIC"
        collect static   Static   "$WD_STATIC"
        collect hybrid   Hyb      "$WD_HYBRID"
        collect wonly    wonly    "$WD_WONLY"
        collect LaWL-D   LaWL_D   "$WD_LAWLD"
        collect LaWL     LaWL     "$WD_LAWL"
    done
done

if [ "$overall_rc" -eq 0 ]; then
    echo "[INFO] compressing workloads -> $BASE_DIR/workloads.tar.gz"
    tar czf "$BASE_DIR/workloads.tar.gz" -C "$BASE_DIR" workloads && rm -rf "$WORKLOADS_DIR"
else
    echo "[WARN] some runs failed; leaving $WORKLOADS_DIR uncompressed for debugging" >&2
fi

echo "Done. Results in $BASE_DIR"
