#!/bin/bash
# Consume workloads generated by gen_simul_skew.sh and run the 9-scheme
# parallel experiment (matches run_simul_rtgc.sh scheme table) for each
# rnum sweep and iteration found under
# $BASE_DIR/workloads/rnum_<S>/<NNN>/.
#
# Usage: ./run_simul_skew.sh BASE_DIR CORE_LIST
#   BASE_DIR   directory produced by gen_simul_skew.sh
#   CORE_LIST  comma-separated core ids, exactly 9 entries
#              (baseline,dynamic,static,hybrid,
#               RTGC-START,RTGC-END,RTGC-PECMAX,RTGC-PECAVG,LaWL)
#
# The explicit CORE_LIST is required so the script works inside a Docker
# container whose cpuset does not include the previously hard-coded 9-15
# range. taskset failed with "Invalid argument" when a core outside the
# container's cpuset was requested.
#
# Semantics of RNUM (0..TASKNUM):
#   With TASKNUM=4 and RNUM=S, the taskset has:
#     S       read-intensive tasks
#     4 - S   write-intensive tasks
#
# argv[10] passed to the simulator = TASKNUM - RNUM so that
# generate_taskset_skew2 sees "# of WRITE-intensive tasks".
# The same value is forwarded at runtime so RR_job_start_q's `skewnum`
# comparison matches the generated taskset polarity.
#
# Behaviour:
#   - Auto-extracts $BASE_DIR/workloads.tar.gz if the workloads/ dir is missing.
#   - Iterates every "<NNN>" directory that has a `.done` marker.
#   - After all iterations finish, tar.gz's the workloads/ dir and deletes the
#     raw copy to save disk. tar.gz is skipped if any iteration failed.
#
# Output layout:
#   $BASE_DIR/rnum_<S>/<scheme_dir>/<prefix>_rrchecker_<NNN>.csv   (per iter)
#   $BASE_DIR/rnum_<S>/<scheme_dir>/<prefix>_updaterate_<NNN>.csv  (per iter)
#   $BASE_DIR/rnum_<S>/<scheme_dir>/<prefix>_lifetime.csv          (appended)
#   $BASE_DIR/rnum_<S>/<scheme_dir>/<prefix>_overhead.csv          (appended)
#   $BASE_DIR/rnum_<S>/<RTGC_*>/<prefix>_token_<NNN>.csv           (RTGC only)
#   $BASE_DIR/rnum_<S>/<RTGC_*>/<prefix>_wl_<NNN>.csv              (RTGC only)
#   $BASE_DIR/rnum_<S>/<RTGC_*>/<prefix>_admission_<NNN>.csv       (RTGC only)

set -u

if [ $# -ne 2 ]; then
    cat >&2 <<USAGE
usage: $0 BASE_DIR CORE_LIST

  BASE_DIR   directory produced by gen_simul_skew.sh
  CORE_LIST  comma-separated core ids, exactly 9 entries
             (baseline,dynamic,static,hybrid,
              RTGC-START,RTGC-END,RTGC-PECMAX,RTGC-PECAVG,LaWL)

example: $0 ./results_skew "44,45,46,47,48,49,50,51,52"
USAGE
    exit 2
fi

BASE_DIR="$1"
CORE_LIST="$2"
BIN="$(readlink -f ./statesimul.out)"

U=0.3
TASKNUM=4
SKEWTYPE=1
RNUMS=(0 1 2 3 4)

# Scheme table.  Index i selects (dir, prefix, args) and CORES[i].
# Mirrors run_simul_rtgc.sh, with SKEWTYPE=1 at argv[7] and __WNUM__
# placeholder at argv[10] (substituted per RNUM iteration).
SCHEME_DIRS=(baseline dynamic static hybrid RTGC-START RTGC-END RTGC-PECMAX RTGC-PECAVG LaWL)
SCHEME_PREFIX=(Baseline Dynamic Static Hyb RTGC_START RTGC_END RTGC_PECMAX RTGC_PECAVG LaWL)
SCHEME_ARGS=(
    "NO     NO        SKIPRR  nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__"              # baseline
    "NO     MOTIVALLY SKIPRR  nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__"              # dynamic
    "NO     NO        BASE005 nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__"              # static
    "NO     MOTIVALLY BASE005 nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__"              # hybrid
    "RTGC   NO        NRTWL   nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__ 0 START"      # RTGC-START
    "RTGC   NO        NRTWL   nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__ 0 END"        # RTGC-END
    "RTGC   NO        NRTWL   nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__ 0 PEC_MAX"    # RTGC-PECMAX
    "RTGC   NO        NRTWL   nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__ 0 PEC_AVG"    # RTGC-PECAVG
    "UTILGC INVW      RR005   nogen 4 __UTIL__ __SKEW__ 0.05 0.95 __WNUM__"              # LaWL
)
# writerank.csv is only meaningful for wflag==14 (LaWL family).  Kept as
# a per-scheme opt-in so the RTGC reject signal isn't muddied.
SCHEME_NEED_WRITERANK=(0 0 0 0 0 0 0 0 1)

NUM_SCHEMES=${#SCHEME_DIRS[@]}

if [ ! -x "$BIN" ]; then
    echo "error: $BIN not found or not executable" >&2
    exit 1
fi

IFS=',' read -r -a CORES <<< "$CORE_LIST"
if [ ${#CORES[@]} -ne "$NUM_SCHEMES" ]; then
    echo "error: CORE_LIST must contain exactly $NUM_SCHEMES core ids (got ${#CORES[@]})" >&2
    exit 1
fi
# Probe with taskset directly instead of comparing to nproc: inside a
# Docker container with --cpuset-cpus=44-52, nproc returns 9 but the
# usable core IDs are 44..52, so a numeric upper bound would reject them.
for core in "${CORES[@]}"; do
    if ! [[ "$core" =~ ^[0-9]+$ ]]; then
        echo "error: core id '$core' is not a non-negative integer" >&2
        exit 1
    fi
    if ! taskset -c "$core" true 2>/dev/null; then
        echo "error: core id '$core' is not available to this process (cpuset?)" >&2
        exit 1
    fi
done

WORKLOADS_DIR="$BASE_DIR/workloads"

if [ ! -d "$WORKLOADS_DIR" ] && [ -f "$BASE_DIR/workloads.tar.gz" ]; then
    echo "[INFO] extracting $BASE_DIR/workloads.tar.gz"
    tar xzf "$BASE_DIR/workloads.tar.gz" -C "$BASE_DIR"
fi

if [ ! -d "$WORKLOADS_DIR" ]; then
    echo "error: $WORKLOADS_DIR not found. Run gen_simul_skew.sh first." >&2
    exit 1
fi

WRITERANK_ABS="$(readlink -f ./writerank.csv 2>/dev/null || true)"
overall_rc=0

for S in "${RNUMS[@]}"; do
    WNUM_ARG=$(( TASKNUM - S ))
    RNUM_SRC="$WORKLOADS_DIR/rnum_$S"
    RNUM_BASE="$BASE_DIR/rnum_$S"

    if [ ! -d "$RNUM_SRC" ]; then
        echo "  warn: no workloads for rnum=$S at $RNUM_SRC; skipping" >&2
        continue
    fi

    for d in "${SCHEME_DIRS[@]}"; do
        mkdir -p "$RNUM_BASE/$d"
    done
    echo "########## read-intensive tasks = $S (write=$WNUM_ARG, util=$U -> $RNUM_BASE) ##########"

    for GENDIR in "$RNUM_SRC"/*/; do
        GENDIR="${GENDIR%/}"
        [ -f "$GENDIR/.done" ] || continue
        IDX=$(basename "$GENDIR")
        echo "=== [rnum=$S] iteration $IDX  ($(date '+%F %T')) ==="

        pids=()
        for i in $(seq 0 $((NUM_SCHEMES-1))); do
            local_wd="$RNUM_BASE/${SCHEME_DIRS[$i]}/_run_$IDX"
            mkdir -p "$local_wd"
            for f in "$GENDIR"/taskparam.csv "$GENDIR"/cyc.csv "$GENDIR"/loc.csv \
                     "$GENDIR"/wr_t*.csv     "$GENDIR"/rd_t*.csv; do
                [ -e "$f" ] || continue
                ln -sf "$(readlink -f "$f")" "$local_wd/$(basename "$f")"
            done
            if [ "${SCHEME_NEED_WRITERANK[$i]}" = "1" ] && \
               [ -n "$WRITERANK_ABS" ] && [ -e "$WRITERANK_ABS" ]; then
                ln -sf "$WRITERANK_ABS" "$local_wd/writerank.csv"
            fi

            args_expanded="${SCHEME_ARGS[$i]//__UTIL__/$U}"
            args_expanded="${args_expanded//__SKEW__/$SKEWTYPE}"
            args_expanded="${args_expanded//__WNUM__/$WNUM_ARG}"
            (
                cd "$local_wd" && \
                taskset -c "${CORES[$i]}" "$BIN" $args_expanded \
                    > /dev/null 2> run.err
            ) &
            pids+=($!)
        done

        rc=0
        for pid in "${pids[@]}"; do
            wait "$pid" || rc=$?
        done
        if [ "$rc" -ne 0 ]; then
            echo "  warn: at least one workload exited non-zero in rnum=$S iter $IDX" >&2
            overall_rc=$rc
        fi

        collect() {
            local scheme_dir="$1"
            local prefix="$2"
            local wd="$RNUM_BASE/$scheme_dir/_run_$IDX"
            local dest="$RNUM_BASE/$scheme_dir"

            for kind in rrchecker updaterate token wl admission; do
                local src="$wd/${prefix}_${kind}.csv"
                [ -f "$src" ] && mv "$src" "$dest/${prefix}_${kind}_${IDX}.csv"
            done
            for kind in lifetime overhead; do
                local src="$wd/${prefix}_${kind}.csv"
                [ -f "$src" ] && cat "$src" >> "$dest/${prefix}_${kind}.csv"
            done
            if [ -s "$wd/run.err" ]; then
                mv "$wd/run.err" "$dest/run_${IDX}.err"
            fi
            rm -rf "$wd"
        }

        for i in $(seq 0 $((NUM_SCHEMES-1))); do
            collect "${SCHEME_DIRS[$i]}" "${SCHEME_PREFIX[$i]}"
        done
    done
done

if [ "$overall_rc" -eq 0 ]; then
    echo "[INFO] compressing workloads -> $BASE_DIR/workloads.tar.gz"
    tar czf "$BASE_DIR/workloads.tar.gz" -C "$BASE_DIR" workloads && rm -rf "$WORKLOADS_DIR"
else
    echo "[WARN] some runs failed; leaving $WORKLOADS_DIR uncompressed for debugging" >&2
fi

echo "Done. Results in $BASE_DIR"
